-- CreateTable
CREATE TABLE "StockReportContext" (
    "ticker" TEXT NOT NULL PRIMARY KEY,
    "capturedAt" DATETIME NOT NULL,
    "recessionLevel" TEXT,
    "recessionLabel" TEXT,
    "recessionLine" TEXT,
    "recessionAlerts" INTEGER,
    "recessionWatches" INTEGER,
    "recessionUnknowns" INTEGER,
    "recessionTotal" INTEGER,
    "macroAsOf" DATETIME,
    "fedBias" TEXT,
    "fedBiasLabel" TEXT,
    "fedHike" REAL,
    "fedHold" REAL,
    "fedCut" REAL,
    "fedAsOf" DATETIME,
    "bubbleScore" REAL,
    "bubbleRegime" TEXT,
    "bubbleStance" TEXT,
    "bubbleScored" INTEGER,
    "bubbleTotal" INTEGER,
    "bubblePriorityFired" BOOLEAN NOT NULL DEFAULT false,
    "bubbleFired" TEXT NOT NULL DEFAULT '',
    "inPortfolio" BOOLEAN NOT NULL DEFAULT false,
    "functionType" TEXT,
    "targetWeight" REAL,
    "holdingThesis" TEXT,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "StockReportContext_ticker_fkey" FOREIGN KEY ("ticker") REFERENCES "StockReport" ("ticker") ON DELETE CASCADE ON UPDATE CASCADE
);
