/**
 * 생산·제조 섹터 — 묶음 정의와 지표를 **이 파일 하나에** 둔다.
 *
 * ⚠ 지표를 더하거나 임계값을 바꿀 때 다른 파일을 건드리지 않는다
 *    (볼트 인수인계 사양서 1-1: 흩어져 있으면 하나 추가에 여러 곳을 고치게 된다).
 *    새 섹터를 만들 때만 `registry.ts`에 한 줄 등록한다.
 */
import { FRED_URL as FRED, type MacroSector } from "../types";

export const sector: MacroSector = {
  group: {
      key: "production",
      name: "생산·제조",
      emoji: "🏭",
      question: "공장이 돌아가고 있나?",
      intro:
        "제조업은 경기 순환의 앞단입니다. 구매관리자지수(PMI)는 기업 구매 담당자에게 직접 물어 만든 지표라 통계보다 빠르고, 50을 넘으면 확장·밑돌면 위축으로 읽습니다.",
      order: 8,
    },
  indicators: [
    {
      key: "ism_mfg",
      name: "ISM 제조업 PMI",
      group: "production",
      source: "MANUAL",
      transform: "level",
      layer: "L6",
      type: "level",
      freq: "m",
      unit: "",
      decimals: 1,
      url: "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-report-on-business/",
      sourceLabel: "수동 입력 · ISM 원보도자료",
      what: "제조업 구매 담당자들에게 지난달보다 나아졌는지 물어 만든 지수입니다. 50이 기준선입니다.",
      why: "통계가 아니라 현장에 직접 물은 것이라 빠르고, 경기 방향을 앞서 보여줍니다.",
      read: "50 위면 확장, 아래면 위축입니다. 45 아래로 내려가면 침체 국면에서 나오던 수준입니다.",
      signal: { op: "lt", warn: 50, alert: 45, rule: "50 미만 위축 · 45 미만 침체 수준" },
      order: 1,
    },
    {
      key: "ism_svc",
      name: "ISM 서비스업 PMI",
      group: "production",
      source: "MANUAL",
      transform: "level",
      layer: "L6",
      type: "level",
      freq: "m",
      unit: "",
      decimals: 1,
      url: "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-report-on-business/",
      sourceLabel: "수동 입력 · ISM 원보도자료",
      what: "서비스업에 같은 방식으로 물어 만든 지수입니다.",
      why: "미국 경제의 대부분은 제조업이 아니라 서비스업입니다. 제조업이 나빠도 서비스가 버티면 경기는 굴러갑니다.",
      read: "제조업이 50 아래인데 서비스가 50 위면, 아직 경기 전체가 꺾인 것은 아니라고 봅니다.",
      order: 2,
    },
    {
      key: "indpro_yoy",
      name: "산업생산 (전년비)",
      group: "production",
      source: "FRED",
      sourceId: "INDPRO",
      transform: "yoy",
      layer: "L3",
      type: "change",
      freq: "m",
      unit: "%",
      decimals: 1,
      url: FRED("INDPRO"),
      sourceLabel: "FRED · INDPRO",
      what: "공장·광산·전력 회사가 실제로 만들어 낸 양이 1년 전보다 얼마나 늘었는지입니다.",
      why: "설문이 아니라 실제 생산량입니다. 심리 지표가 맞았는지 확인하는 자리입니다.",
      read: "마이너스로 내려가면 실물이 실제로 줄고 있다는 뜻입니다.",
      order: 3,
    },
    {
      key: "phil_fed",
      name: "필라델피아 연준 제조업지수",
      group: "production",
      source: "FRED",
      sourceId: "GACDFSA066MSFRBPHI",
      transform: "level",
      layer: "L6",
      type: "level",
      freq: "m",
      unit: "",
      decimals: 1,
      url: FRED("GACDFSA066MSFRBPHI"),
      sourceLabel: "FRED · GACDFSA066MSFRBPHI",
      what: "필라델피아 연준이 관할 지역 제조업체에 묻는 체감 경기입니다. 0이 기준선입니다.",
      why: "ISM보다 먼저 나옵니다. 이번 달 제조업이 어떨지 미리 엿볼 수 있습니다.",
      read: "0 위면 확장, 아래면 위축입니다. 월별 변동이 큰 편이라 흐름으로 봅니다.",
      order: 4,
    },
    /*
     * ── 공급 쪽 세 지표 ─────────────────────────────────────────────
     * ⚠ 여기서부터는 「경기가 좋은가」가 아니라 **「수요를 죽이지 않고 물가를 잡을 수 있는가」**를
     *   재는 지표다. 물가를 금리로 누르는 길(수요 축소)과 생산성으로 흡수하는 길(공급 확대)이
     *   갈리는 자리이고, `lib/macro/capital.ts`의 두 격차가 이 셋을 입력으로 쓴다.
     * ⚠ 셋 다 **원 발표 기관은 FRED가 아니다**(BLS·BEA). 용어 사전이 그쪽을 댄다.
     */
    {
      key: "prod_yoy",
      name: "노동생산성 (전년비)",
      group: "production",
      source: "FRED",
      // ⚠ 수준 계열이다. `PRS85006092`는 같은 생산성이지만 **연율 분기변화**여서
      //    전년비로 읽으면 값이 절반 가까이 작아진다. 전년비는 우리가 계산한다.
      sourceId: "OPHNFB",
      transform: "yoy",
      layer: "L2",
      type: "change",
      freq: "q",
      unit: "%",
      decimals: 2,
      url: FRED("OPHNFB"),
      sourceLabel: "FRED · OPHNFB (원 발표: 미 노동통계국 BLS)",
      what: "한 시간 일해서 만들어 내는 양이 1년 전보다 얼마나 늘었는지입니다(미국 비농업 부문).",
      why: "공급 쪽 힘의 핵심입니다. 이것이 오르면 **같은 노동으로 더 많이 만들 수 있어, 수요를 줄이지 않고도 물가 압력이 낮아질 수 있습니다.** 금리로 수요를 눌러 물가를 잡는 길과, 생산성으로 공급을 늘려 흡수하는 길이 여기서 갈립니다.",
      read: "2% 안팎이면 2000년대 중반 이후 기준으로 높은 편입니다. ⚠ 한 분기는 크게 튀므로 4분기 평균으로 보세요. ⚠ 그리고 생산성이 올라도 물가가 **곧바로** 내려가지는 않습니다 — 늘어난 공급이 실제로 쓰일 때까지 시차가 있고, 그 사이 수요가 더 빨리 늘면 물가는 오히려 오릅니다.",
      order: 5,
    },
    {
      key: "ulc_yoy",
      name: "단위노동비용 (전년비)",
      group: "production",
      source: "FRED",
      sourceId: "ULCNFB",
      transform: "yoy",
      layer: "L2",
      type: "change",
      freq: "q",
      unit: "%",
      decimals: 2,
      url: FRED("ULCNFB"),
      sourceLabel: "FRED · ULCNFB (원 발표: 미 노동통계국 BLS)",
      what: "물건 하나를 만드는 데 드는 인건비입니다. 임금이 올라도 생산성이 더 오르면 내려갑니다.",
      why: "임금 상승이 물가로 번지는지를 가르는 자리입니다. **임금이 올라도 이 값이 얌전하면 그 임금은 생산성이 내고 있는 것**이고, 그때 임금 상승은 인플레이션의 근거가 되지 못합니다.",
      read: "연준의 물가 목표(2%)와 견줘 보세요. 이 값이 그 아래에서 움직이면 인건비 쪽에서 오는 물가 압력은 크지 않습니다. 노동생산성과 **함께** 보셔야 원인이 갈립니다.",
      order: 6,
    },
    {
      key: "ngdp_yoy",
      name: "명목 GDP (전년비)",
      group: "production",
      source: "FRED",
      sourceId: "GDP",
      transform: "yoy",
      layer: "L2",
      type: "change",
      freq: "q",
      unit: "%",
      decimals: 2,
      url: FRED("GDP"),
      sourceLabel: "FRED · GDP (원 발표: 미 경제분석국 BEA)",
      what: "물가 상승분을 빼지 않은, 지금 돈 단위로 센 경제 규모가 1년 전보다 얼마나 커졌는지입니다.",
      why: "⚠ **부채를 갚는 힘은 실질이 아니라 명목으로 자랍니다.** 세금도 이자도 명목으로 내기 때문입니다. 이 값이 국채 금리보다 높으면 경제가 이자보다 빨리 자라고 있다는 뜻이고, 그래서 정부 부채가 굴러갑니다.",
      read: "10년 국채 금리와 견줘 보세요(성장–조달 격차). ⚠ 다만 이것은 **부채 지속가능성** 질문이고, 민간이 빌려서 투자할 값이 있는지는 **다른 질문**입니다 — 둘은 반대로 나올 수 있습니다.",
      order: 7,
    },
  ],
};
