/**
 * 금리 섹터 — 묶음 정의와 지표를 **이 파일 하나에** 둔다.
 *
 * ⚠ 지표를 더하거나 임계값을 바꿀 때 다른 파일을 건드리지 않는다
 *    (볼트 인수인계 사양서 1-1: 흩어져 있으면 하나 추가에 여러 곳을 고치게 된다).
 *    새 섹터를 만들 때만 `registry.ts`에 한 줄 등록한다.
 */
import { FRED_URL as FRED, type MacroSector } from "../types";

export const sector: MacroSector = {
  group: {
      key: "rates",
      name: "금리",
      emoji: "🏦",
      question: "돈을 빌리는 값이 얼마인가?",
      intro:
        "금리는 모든 자산 가격의 기준점입니다. 금리가 오르면 예금·채권이 매력적이 되고, 같은 이익을 내는 주식의 값어치는 상대적으로 깎입니다. 특히 미 국채 10년물은 전 세계 주식 밸류에이션의 할인율로 쓰여서, 이 숫자가 움직이면 주가가 따라 흔들립니다.",
      order: 1,
    },
  indicators: [
    {
      key: "fed_funds",
      name: "미국 기준금리",
      group: "rates",
      source: "FRED",
      sourceId: "FEDFUNDS",
      transform: "level",
      unit: "%",
      decimals: 2,
      url: FRED("FEDFUNDS"),
      sourceLabel: "FRED · FEDFUNDS",
      what: "미국 중앙은행(연준)이 정하는 정책금리입니다. 은행끼리 하루짜리 돈을 빌릴 때 쓰는 금리로, 세상 모든 금리의 출발점입니다.",
      why: "이 금리가 오르면 예금·대출·채권 금리가 줄줄이 따라 오르고, 주식은 상대적으로 매력이 줄어듭니다. 반대로 내리면 위험자산에 돈이 돌아옵니다.",
      read: "올리는 국면인지 내리는 국면인지가 방향이고, 절대 수준보다 '앞으로 어디로 갈까'를 시장이 더 크게 반영합니다.",
      headline: true,
      order: 1,
    },
    {
      key: "kr_policy_rate",
      name: "한국 기준금리",
      group: "rates",
      source: "MANUAL",
      transform: "level",
      unit: "%",
      decimals: 2,
      url: "https://www.bok.or.kr/portal/singl/baseRate/list.do?dataSeCd=01&menuNo=200643",
      sourceLabel: "수동 입력 · 한국은행 금통위",
      what: "한국은행이 정하는 정책금리입니다. 국내 예금·대출 금리와 원화 유동성이 여기서 갈립니다.",
      why: "미국과의 금리 차이가 벌어지면 원화가 약해지기 쉽습니다. 한국에서 투자한다면 미국 금리만큼이나 중요한 숫자입니다.",
      read: "미국 기준금리와 나란히 놓고 차이(한미 금리차)를 봅니다. 차이가 클수록 환율에 압력이 됩니다.",
      order: 2,
    },
    {
      key: "ust10y",
      name: "미 국채 10년",
      group: "rates",
      source: "FRED",
      sourceId: "DGS10",
      transform: "level",
      unit: "%",
      decimals: 2,
      url: FRED("DGS10"),
      sourceLabel: "FRED · DGS10",
      what: "미국 정부가 10년 동안 돈을 빌리며 주는 이자율입니다. 세계에서 가장 안전하다고 여겨지는 자산의 값입니다.",
      why: "주식의 가치를 계산할 때 미래 이익을 현재로 당겨오는 '할인율'로 쓰입니다. 이 금리가 오르면 특히 먼 미래의 이익을 파는 성장주가 먼저 눌립니다.",
      read: "빠르게 오르는 구간이 주식에 가장 아픕니다. 절대 수준보다 오르는 속도를 봅니다.",
      order: 3,
    },
    {
      key: "ust2y",
      name: "미 국채 2년",
      group: "rates",
      source: "FRED",
      sourceId: "DGS2",
      transform: "level",
      unit: "%",
      decimals: 2,
      url: FRED("DGS2"),
      sourceLabel: "FRED · DGS2",
      what: "미국 정부가 2년간 돈을 빌리며 주는 이자율입니다.",
      why: "만기가 짧아 '연준이 앞으로 금리를 어떻게 할까'에 대한 시장의 예상을 가장 잘 반영합니다.",
      read: "기준금리보다 낮아지면 시장이 금리 인하를 기대하고 있다는 뜻입니다.",
      order: 4,
    },
    {
      key: "t10y2y",
      name: "10년-2년 금리차",
      group: "rates",
      source: "FRED",
      sourceId: "T10Y2Y",
      transform: "level",
      unit: "%p",
      decimals: 2,
      url: FRED("T10Y2Y"),
      sourceLabel: "FRED · T10Y2Y",
      what: "10년 금리에서 2년 금리를 뺀 값입니다. 보통은 오래 빌려줄수록 이자를 더 받으니 플러스입니다.",
      why: "이 값이 마이너스가 되는 것을 '금리 역전'이라 부릅니다. 과거 미국의 침체 앞에서 거의 매번 나타났던, 가장 유명한 선행 신호입니다.",
      read: "0 아래로 내려가면 시장이 앞으로의 경기를 나쁘게 보고 있다는 뜻입니다. 다만 역전에서 실제 침체까지는 보통 1년 안팎의 시차가 있습니다.",
      signal: { op: "lt", warn: 0.2, alert: 0, rule: "0 아래면 금리 역전(경고)" },
      order: 5,
    },
    {
      key: "hy_spread",
      name: "하이일드 스프레드",
      group: "rates",
      source: "FRED",
      sourceId: "BAMLH0A0HYM2",
      transform: "level",
      unit: "%p",
      decimals: 2,
      url: FRED("BAMLH0A0HYM2"),
      sourceLabel: "FRED · BAMLH0A0HYM2",
      what: "신용도가 낮은 기업이 국채보다 얼마나 더 높은 이자를 물어야 돈을 빌릴 수 있는지입니다.",
      why: "돈줄이 막히는 순간 이 값이 먼저 튑니다. 주식보다 빠르게 위험을 알려주는 편입니다.",
      read: "완만히 오르는 것은 정상 범위, 단기간에 급등하면 신용경색 신호로 봅니다.",
      signal: { op: "gt", warn: 4.5, alert: 6, rule: "급등하면 신용경색(4.5%p 주의 · 6%p 경고)" },
      order: 6,
    },
    {
      key: "vix",
      name: "VIX 변동성지수",
      group: "rates",
      source: "FRED",
      sourceId: "VIXCLS",
      transform: "level",
      unit: "",
      decimals: 1,
      url: FRED("VIXCLS"),
      sourceLabel: "FRED · VIXCLS",
      what: "앞으로 30일간 S&P500이 얼마나 출렁일지에 대한 시장의 예상입니다. '공포지수'라 부릅니다.",
      why: "값이 튀는 순간은 대개 이미 팔린 뒤입니다. 공포의 크기를 재는 눈금으로 씁니다.",
      read: "20을 넘으면 불안, 30을 넘으면 공포 구간으로 봅니다. 평온한 구간이 길수록 방심하기 쉽습니다.",
      signal: { op: "gt", warn: 20, alert: 30, rule: "20 넘으면 경계 · 30 넘으면 공포" },
      order: 7,
    },
  ],
};
