/**
 * GCRM v2 — 지표 정의 (명세 §2-3).
 *
 * ## ⚠ 새 수집 파이프라인이 아니다
 * 모든 지표는 포털이 **이미 매일 받고 있는 계열**(`lib/macro/registry.ts` · D1 `MacroPoint`)을 가리킨다.
 * `series`가 그 키다. 같은 지표가 사이트 안에서 두 값을 갖는 사고를 막는 유일한 방법이다(명세 §C-1).
 *
 * ## ⚠ `portalTransform`과 `transform`은 다른 것이다 — 겹쳐 쓰면 두 번 변환된다
 * `MacroPoint`에는 **원값**이 들어 있다. 화면은 레지스트리의 `transform`(yoy 등)을 읽을 때 적용한다.
 * - `portalTransform` — 레지스트리가 쓰는 변환. **대조용으로 적어 둔 사실**이다(테스트가 레지스트리와 맞춰 본다).
 * - `transform` — 그 위에 GCRM이 **더** 거는 변환. 기본은 `level`(더 걸지 않는다).
 *   여기에 `yoy`를 또 적으면 전년비의 전년비가 된다.
 *
 * ## 점수 축 (단계 0 원칙 2)
 * `polarity: +1`은 **값이 높을수록 자본에 우호**, `-1`은 불리다. 정규화의 마지막에 `-1`이면
 * `100 − score`로 뒤집고, **뒤집은 뒤에는 raw와 섞지 않는다.**
 * ⚠ 한 지표가 기둥마다 뜻이 달라지는 경우(달러인덱스)는 여기서 뒤집지 않고
 *   `pillars.ts`의 `polarity` 덮어쓰기로 **이유와 함께** 처리한다.
 *
 * ## ⚠ `freq`는 선언이 아니라 실측이다 (조사 §2-1)
 * 레지스트리가 `d`라고 적어도 2024년 관측이 12점이면 그 계열은 월간이다. 선언을 믿고 5일 창을
 * 잡으면 **조용히 5개월 창**이 된다. 실측이 다른 계열에는 주석으로 근거를 남겼다.
 *
 * ## 이력 길이를 함께 적는 이유 (조사 §2-2)
 * `minObs`를 통과해도 3년짜리의 「99번째 백분위」는 3년 중 최악일 뿐이다.
 * 화면이 그 구분을 말할 수 있도록 `historyStart`·`points`를 정의에 남긴다(2026-09-19 실측).
 */
import { WINDOW_OBS } from "./model";
import type { EvidenceKind } from "./model";

/** 명세 §2-10 — 승격·확인에 쓰는 독립 채널 6개. 정의는 `channels.ts`. */
export type ChannelCode = "PRICE" | "CREDIT" | "FUNDING" | "RATES" | "FX" | "COMMODITY";

/** 공표 주기. 저빈도 지표가 어느 축에 참여하는지를 이 값이 정한다(§2-4). */
export type Freq = "d" | "w" | "m" | "q";

export type GcrmIndicator = {
  /** GCRM 안에서의 코드. 지금은 포털 키와 같게 둔다 — 다르면 대조가 안 된다. */
  code: string;
  nameKo: string;
  /** ⚠ 포털 `MacroIndicator.key`. 이것이 D1 `MacroPoint.seriesKey`다. */
  series: string;
  source: string;
  seriesId?: string;
  /** ⚠ 실측 주기(선언이 아니다). */
  freq: Freq;
  /** 레지스트리가 쓰는 변환 — 대조용 사실. 테스트가 맞춰 본다. */
  portalTransform: string;
  /** GCRM이 **더** 거는 변환. 기본 `level`. */
  transform: "level" | "yoy" | "mom" | "diff" | "ratio";
  /** +1 우호 · −1 불리 */
  polarity: 1 | -1;
  scaler: "pct_rank" | "zscore_cdf";
  window: "expanding" | "rolling";
  /** 미달이면 예외가 아니라 `MISSING`이다. */
  minObs: number;
  maxWindow: number;
  winsor: [number, number];
  channels: ChannelCode[];
  evidence: EvidenceKind;
  /** 2026-09-19 운영 D1 실측. 없으면 미수집. */
  historyStart: string | null;
  points: number;
  /** 파생 계열처럼 `points`가 0인 이유. ⚠ 「이력이 없다」와 「저장하지 않는다」는 다른 것이다. */
  historyNote?: string;
  enabled: boolean;
  /** `enabled: false`인 이유. ⚠ 끈 지표에는 반드시 적는다(검증기가 강제한다). */
  disabledReason?: string;
  glossary?: string;
};

export const GCRM_INDICATORS: GcrmIndicator[] = [
  {
    code: "reserves",
    nameKo: "은행 지급준비금",
    series: "reserves",
    source: "FRED", seriesId: "WRESBAL",
    freq: "w",
    portalTransform: "levelM",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "2002-12-18",
    points: 1240,
    enabled: true,
  },
  {
    code: "fed_assets",
    nameKo: "연준 총자산",
    series: "fed_assets",
    source: "FRED", seriesId: "WALCL",
    freq: "w",
    portalTransform: "levelM",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "2002-12-18",
    points: 1240,
    enabled: true,
  },
  /** 잔액이 늘면 유동성을 흡수한다 */
  {
    code: "rrp",
    nameKo: "역레포 잔액 (ON RRP)",
    series: "rrp",
    source: "FRED", seriesId: "RRPONTSYD",
    freq: "d",
    portalTransform: "levelK",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "2003-02-07",
    points: 3329,
    enabled: true,
  },
  /** FIMA 풀 사용이 늘면 역외 달러 조달이 빡빡하다 */
  {
    code: "rrp_foreign",
    nameKo: "해외 공적기관 역레포 (FIMA 풀)",
    series: "rrp_foreign",
    source: "FRED", seriesId: "WLRRAFOIAL",
    freq: "w",
    portalTransform: "levelM",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["FUNDING", "FX"],
    evidence: "official",
    historyStart: "2002-12-18",
    points: 1240,
    enabled: true,
  },
  /** 재무부 계정이 불면 시중에서 현금이 빠진다 */
  {
    code: "tga",
    nameKo: "재무부 일반계정 (TGA)",
    series: "tga",
    source: "FRED", seriesId: "WDTGAL",
    freq: "w",
    portalTransform: "levelM",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "2002-12-18",
    points: 1240,
    enabled: true,
  },
  /** 자금시장 스트레스의 1차 지표 */
  {
    code: "sofr_iorb",
    nameKo: "SOFR − IORB (자금시장 스트레스)",
    series: "sofr_iorb",
    source: "DERIVED",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "2021-07-29",
    points: 1879,
    historyNote:
      "파생 — 저장하지 않고 읽을 때 sofr − iorb로 합성한다. 이력은 늦게 시작하는 iorb(2021-07-29)가 정한다.",
    enabled: true,
  },
  {
    code: "sofr_dispersion",
    nameKo: "SOFR 분포 폭 (99번째 − 1번째 백분위)",
    series: "sofr_dispersion",
    source: "DERIVED",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "2018-04-03",
    points: 2111,
    historyNote:
      "파생 — sofr99 − sofr1. 이력은 두 성분과 같다.",
    enabled: true,
  },
  {
    code: "sofr_rvol",
    nameKo: "SOFR 변동성 (20일 실현, bp)",
    series: "sofr_rvol",
    source: "DERIVED",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "2018-04-03",
    points: 2093,
    historyNote:
      "파생 — sofr의 20일 실현변동성. 창 20일만큼 늦게 시작한다.",
    enabled: true,
  },
  {
    code: "m2_yoy",
    nameKo: "M2 통화량 (전년비)",
    series: "m2_yoy",
    source: "FRED", seriesId: "M2SL",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["FUNDING"],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 439,
    enabled: true,
  },
  /** 응찰률이 높을수록 수요가 두껍다 */
  {
    code: "auction10y_btc",
    nameKo: "10년 국채 입찰 응찰률 (명목)",
    series: "auction10y_btc",
    source: "TREASURY", seriesId: "auction10y:bid_to_cover",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "2014-01-08",
    points: 154,
    enabled: true,
  },
  /** 낙찰금리가 높을수록 조달이 비싸다 */
  {
    code: "auction10y_yield",
    nameKo: "10년 국채 입찰 낙찰금리 (명목)",
    series: "auction10y_yield",
    source: "TREASURY", seriesId: "auction10y:high_yield",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "2014-01-08",
    points: 154,
    enabled: true,
  },
  /** 이표채 비중이 커지면 듀레이션 공급 압력이 커진다 */
  {
    code: "tsy_coupon_share",
    nameKo: "시장성 국채 중 이표채(Notes·Bonds) 비중",
    series: "tsy_coupon_share",
    source: "TREASURY", seriesId: "mspd:coupon_share",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "2014-01-31",
    points: 152,
    enabled: true,
  },
  /** ⚠ CREDIT 채널의 장기 골격 — 1990년부터 있다 */
  {
    code: "baa_spread",
    nameKo: "Baa 회사채 − 10년 국채 금리차",
    series: "baa_spread",
    source: "DERIVED",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9184,
    historyNote:
      "파생 — baa_yield − ust10y. ⚠ CREDIT 채널에서 **유일하게 30년 이력을 가진 지표**다.",
    enabled: true,
  },
  /** ⚠ FRED가 3년 창만 준다 · 우리 L2가 아카이브다 — 지우지 말 것 */
  {
    code: "hy_spread",
    nameKo: "하이일드 스프레드",
    series: "hy_spread",
    source: "FRED", seriesId: "BAMLH0A0HYM2",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "2023-08-07",
    points: 818,
    enabled: true,
  },
  /** ⚠ hy_spread와 같다 — 지우지 말 것 */
  {
    code: "ig_spread",
    nameKo: "투자적격 회사채 스프레드",
    series: "ig_spread",
    source: "FRED", seriesId: "BAMLC0A0CM",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "2023-08-22",
    points: 806,
    enabled: true,
  },
  {
    code: "bank_credit_yoy",
    nameKo: "은행 총신용 (전년비)",
    series: "bank_credit_yoy",
    source: "FRED", seriesId: "TOTBKCR",
    freq: "w",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1990-01-03",
    points: 1915,
    enabled: true,
  },
  {
    code: "deposits_yoy",
    nameKo: "은행 예금 (전년비)",
    series: "deposits_yoy",
    source: "FRED", seriesId: "DPSACBW027SBOG",
    freq: "w",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1990-01-03",
    points: 1915,
    enabled: true,
  },
  {
    code: "ci_loans_yoy",
    nameKo: "기업 대출 C&I (전년비)",
    series: "ci_loans_yoy",
    source: "FRED", seriesId: "BUSLOANS",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 440,
    enabled: true,
  },
  /** 순비율이 오르면 은행이 조인 것이다 */
  {
    code: "sloos_ci",
    nameKo: "은행 대출태도 (C&I 기준 강화 비율)",
    series: "sloos_ci",
    source: "FRED", seriesId: "DRTSCILM",
    freq: "q",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1990-04-01",
    points: 146,
    enabled: true,
  },
  /** 레버리지 축적 — 수준이 아니라 속도를 본다 */
  /**
   * 재정 우위 세 자리 (2026-09-20, P1). ⚠ **금액이 아니라 비율**로 붙였다 —
   * 명목 금액은 물가·경제 규모를 따라 커져 백분위가 늘 최고치에 붙는다(움직이지 않는 지표).
   * 근거와 실측 범위는 `lib/macro/sectors/fiscal.ts` 머리말에 있다.
   */
  {
    code: "fed_outlays_receipts",
    nameKo: "연방 지출 ÷ 세입",
    series: "fed_outlays_receipts",
    source: "DERIVED",
    freq: "q",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: null,
    points: 0,
    historyNote:
      "2026-09-20에 붙인 계열이라 아직 D1에 값이 없다. 성분(FGRECPT·FGEXPND)은 1947년부터 있고 수집은 1990-01-01부터 받는다(`ingest.ts` HISTORY_START).",
    enabled: true,
  },
  {
    code: "fed_interest_receipts",
    nameKo: "연방 이자지출 ÷ 세입",
    series: "fed_interest_receipts",
    source: "DERIVED",
    freq: "q",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: null,
    points: 0,
    historyNote:
      "2026-09-20에 붙인 계열. ⚠ 1990년대 초(27%대)가 지금(20.9%)보다 높다 — 백분위가 최고치에 붙어 있지 않다는 것을 실측으로 확인하고 넣었다.",
    enabled: true,
  },
  /** 시장이 실제로 떠안는 물량. ⚠ 잔액은 거의 언제나 사상 최대라 **증가율**로 본다. */
  {
    code: "treasury_marketable",
    nameKo: "시장성 국채 잔액 (전년비)",
    series: "treasury_marketable",
    source: "TREASURY", seriesId: "mspd:total_marketable",
    freq: "m",
    portalTransform: "level",
    transform: "yoy",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 36,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: null,
    points: 0,
    historyNote:
      "MSPD 표 1의 「Total Marketable」은 이미 받고 있었지만(비중 계산의 분모) 계열로 저장하지 않았다. 2026-09-20에 계열로 노출했다 — 수집 뒤에 채워진다.",
    enabled: true,
  },
  {
    code: "total_debt_yoy",
    nameKo: "미국 총부채 (전 부문, 전년비)",
    series: "total_debt_yoy",
    source: "FRED", seriesId: "TCMDO",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "ust10y",
    nameKo: "미 국채 10년",
    series: "ust10y",
    source: "FRED", seriesId: "DGS10",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9184,
    enabled: true,
  },
  {
    code: "ust2y",
    nameKo: "미 국채 2년",
    series: "ust2y",
    source: "FRED", seriesId: "DGS2",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9184,
    enabled: true,
  },
  {
    code: "ust30y",
    nameKo: "미 국채 30년",
    series: "ust30y",
    source: "FRED", seriesId: "DGS30",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9184,
    enabled: true,
  },
  /** 역전은 스트레스, 가팔라지면 정상화 */
  {
    code: "t10y2y",
    nameKo: "10년-2년 금리차",
    series: "t10y2y",
    source: "FRED", seriesId: "T10Y2Y",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9184,
    enabled: true,
  },
  {
    code: "t30y2y",
    nameKo: "30년-2년 금리차 (곡선 기울기)",
    series: "t30y2y",
    source: "DERIVED",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9184,
    historyNote:
      "파생 — ust30y − ust2y.",
    enabled: true,
  },
  /** 실질금리가 오르면 자본 조달이 비싸진다 */
  {
    code: "real10",
    nameKo: "실질 10년 금리 (TIPS)",
    series: "real10",
    source: "FRED", seriesId: "DFII10",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "2003-01-02",
    points: 5932,
    enabled: true,
  },
  /** 기대인플레 상승은 통화 규율 압력이다 */
  {
    code: "bei10",
    nameKo: "기대 인플레이션 (10년)",
    series: "bei10",
    source: "FRED", seriesId: "T10YIE",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "2003-01-02",
    points: 5932,
    enabled: true,
  },
  {
    code: "infl_exp_5y",
    nameKo: "기대 인플레이션 (5년)",
    series: "infl_exp_5y",
    source: "FRED", seriesId: "T5YIE",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "2003-01-02",
    points: 5932,
    enabled: true,
  },
  {
    code: "term_premium",
    nameKo: "10년 텀 프리미엄 (ACM)",
    series: "term_premium",
    source: "FRED", seriesId: "THREEFYTP10",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9160,
    enabled: true,
  },
  /** MOVE 대용 — ICE 라이선스 없이 같은 것을 잰다 */
  {
    code: "ust10y_rvol",
    nameKo: "10년물 국채 금리 실현변동성 (20일, bp)",
    series: "ust10y_rvol",
    source: "DERIVED",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9160,
    historyNote:
      "파생 — ust10y의 20일 실현변동성. MOVE 대용.",
    enabled: true,
  },
  {
    code: "mortgage30",
    nameKo: "30년 고정 모기지 금리",
    series: "mortgage30",
    source: "FRED", seriesId: "MORTGAGE30US",
    freq: "w",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-05",
    points: 1916,
    enabled: true,
  },
  {
    code: "dff",
    nameKo: "미국 실효 연방기금금리 (일간)",
    series: "dff",
    source: "FRED", seriesId: "DFF",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 13409,
    enabled: true,
  },
  /** 연방기금 선물이 보는 다음 달 평균 실효금리 */
  {
    code: "zq_front",
    nameKo: "선물 내재 정책금리 (근월물)",
    series: "zq_front",
    source: "YAHOO", seriesId: "ZQ=F",
    freq: "d",
    portalTransform: "price100",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "market",
    historyStart: "2016-09-13",
    points: 2519,
    enabled: true,
  },
  /** ⚠ VIX는 PRICE다 — 주식과 주식 변동성을 별개 채널로 세지 않는다 */
  {
    code: "vix",
    nameKo: "VIX 변동성지수",
    series: "vix",
    source: "FRED", seriesId: "VIXCLS",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["PRICE"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9276,
    enabled: true,
  },
  /** ⚠ PRICE */
  {
    code: "vvix",
    nameKo: "VVIX (VIX의 변동성)",
    series: "vvix",
    source: "YAHOO", seriesId: "^VVIX",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["PRICE"],
    evidence: "market",
    historyStart: "2016-09-12",
    points: 2511,
    enabled: true,
  },
  /** ⚠ PRICE — 꼬리 위험 */
  {
    code: "skew",
    nameKo: "SKEW 지수 (꼬리 위험)",
    series: "skew",
    source: "YAHOO", seriesId: "^SKEW",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["PRICE"],
    evidence: "market",
    historyStart: "2016-09-12",
    points: 2464,
    enabled: true,
  },
  {
    code: "spx_etf",
    nameKo: "S&P 500 (기준)",
    series: "spx_etf",
    source: "YAHOO", seriesId: "SPY",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["PRICE"],
    evidence: "market",
    historyStart: "2016-08-29",
    points: 2528,
    enabled: true,
  },
  /** ⚠ 2025년까지 월간이다 — 파도에 쓸 수 없다 */
  // ⚠ 레지스트리는 freq "d"로 선언하지만 실측은 월간이다(2024년 12점).
  {
    code: "sox",
    nameKo: "필라델피아 반도체지수 (SOX)",
    series: "sox",
    source: "YAHOO", seriesId: "^SOX",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["PRICE"],
    evidence: "market",
    historyStart: "1994-06-01",
    points: 449,
    enabled: true,
  },
  /** 달러 강세는 역외 달러 유동성을 조인다 (⚠ 달러 네트워크 기둥에서는 부호를 뒤집는다) */
  {
    code: "dxy",
    nameKo: "달러인덱스 (DXY)",
    series: "dxy",
    source: "YAHOO", seriesId: "DX-Y.NYB",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["FX"],
    evidence: "market",
    historyStart: "2016-08-22",
    points: 2534,
    enabled: true,
  },
  {
    code: "usdjpy",
    nameKo: "엔/달러 환율",
    series: "usdjpy",
    source: "YAHOO", seriesId: "JPY=X",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["FX"],
    evidence: "market",
    historyStart: "1990-01-02",
    points: 9226,
    enabled: true,
  },
  {
    code: "usdcny",
    nameKo: "위안/달러 환율",
    series: "usdcny",
    source: "YAHOO", seriesId: "CNY=X",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["FX"],
    evidence: "market",
    historyStart: "1990-01-02",
    points: 9166,
    enabled: true,
  },
  /** 에너지 가격은 엔진 온도로 들어온다 */
  {
    code: "brent",
    nameKo: "브렌트유 (현물)",
    series: "brent",
    source: "FRED", seriesId: "DCOILBRENTEU",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["COMMODITY"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9308,
    enabled: true,
  },
  {
    code: "wti",
    nameKo: "WTI 유가 (현물)",
    series: "wti",
    source: "FRED", seriesId: "DCOILWTICO",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["COMMODITY"],
    evidence: "official",
    historyStart: "1990-01-02",
    points: 9226,
    enabled: true,
  },
  {
    code: "natgas",
    nameKo: "천연가스 (헨리허브)",
    series: "natgas",
    source: "FRED", seriesId: "DHHNGSP",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["COMMODITY"],
    evidence: "official",
    historyStart: "1997-01-07",
    points: 7455,
    enabled: true,
  },
  /** 금 강세는 통화가치 희석 기대의 확인이다 */
  {
    code: "gold",
    nameKo: "금 (COMEX 최근월)",
    series: "gold",
    source: "YAHOO", seriesId: "GC=F",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["COMMODITY"],
    evidence: "market",
    historyStart: "2016-08-22",
    points: 2533,
    enabled: true,
  },
  /** 실물 수요의 대리 — ⚠ 월간이다 */
  {
    code: "copper",
    nameKo: "구리 (Dr. Copper)",
    series: "copper",
    source: "FRED", seriesId: "PCOPPUSDM",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["COMMODITY"],
    evidence: "official",
    historyStart: "1992-01-01",
    points: 415,
    enabled: true,
  },
  {
    code: "core_cpi_yoy",
    nameKo: "근원 CPI (전년비)",
    series: "core_cpi_yoy",
    source: "FRED", seriesId: "CPILFESL",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 439,
    enabled: true,
  },
  {
    code: "core_pce_yoy",
    nameKo: "근원 PCE (전년비)",
    series: "core_pce_yoy",
    source: "FRED", seriesId: "PCEPILFE",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 439,
    enabled: true,
  },
  {
    code: "cpi_yoy",
    nameKo: "소비자물가 CPI (전년비)",
    series: "cpi_yoy",
    source: "FRED", seriesId: "CPIAUCSL",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 439,
    enabled: true,
  },
  {
    code: "ppi_yoy",
    nameKo: "생산자물가 PPI (전년비)",
    series: "ppi_yoy",
    source: "FRED", seriesId: "PPIACO",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 440,
    enabled: true,
  },
  {
    code: "wages_yoy",
    nameKo: "평균 시간당 임금 (전년비)",
    series: "wages_yoy",
    source: "FRED", seriesId: "CES0500000003",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "2006-03-01",
    points: 246,
    enabled: true,
  },
  /** 단위노동비용 — 생산성으로 흡수되지 못한 임금 */
  {
    code: "ulc_yoy",
    nameKo: "단위노동비용 (전년비)",
    series: "ulc_yoy",
    source: "FRED", seriesId: "ULCNFB",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "prod_yoy",
    nameKo: "노동생산성 (전년비)",
    series: "prod_yoy",
    source: "FRED", seriesId: "OPHNFB",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "output_per_worker_yoy",
    nameKo: "근로자당 산출 (전년비)",
    series: "output_per_worker_yoy",
    source: "FRED", seriesId: "PRS85006163",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "real_comp_yoy",
    nameKo: "실질 시간당 보수 (전년비)",
    series: "real_comp_yoy",
    source: "FRED", seriesId: "COMPRNFB",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "pot_gdp_yoy",
    nameKo: "잠재산출 (전년비)",
    series: "pot_gdp_yoy",
    source: "FRED", seriesId: "GDPPOT",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 147,
    enabled: true,
  },
  {
    code: "pnfi_yoy",
    nameKo: "민간 비주거 고정투자 (전년비)",
    series: "pnfi_yoy",
    source: "FRED", seriesId: "PNFI",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "equipment_inv_yoy",
    nameKo: "장비 투자 (전년비)",
    series: "equipment_inv_yoy",
    source: "FRED", seriesId: "Y033RC1Q027SBEA",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "ip_inv_yoy",
    nameKo: "지식재산 투자 (전년비)",
    series: "ip_inv_yoy",
    source: "FRED", seriesId: "Y001RC1Q027SBEA",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  /** AI 수요의 실물 흔적 */
  {
    code: "power_ip_yoy",
    nameKo: "전력 생산·송전 (전년비)",
    series: "power_ip_yoy",
    source: "FRED", seriesId: "IPG2211S",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 440,
    enabled: true,
  },
  /** AI 장비 가격 압력 */
  {
    code: "semi_ppi_yoy",
    nameKo: "반도체 생산자물가 (전년비)",
    series: "semi_ppi_yoy",
    source: "FRED", seriesId: "PCU334413334413",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 440,
    enabled: true,
  },
  {
    code: "corp_profits_yoy",
    nameKo: "기업이익 (실현 · 세후, 전년비)",
    series: "corp_profits_yoy",
    source: "FRED", seriesId: "CP",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "ngdp_yoy",
    nameKo: "명목 GDP (전년비)",
    series: "ngdp_yoy",
    source: "FRED", seriesId: "GDP",
    freq: "q",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 146,
    enabled: true,
  },
  {
    code: "indpro_yoy",
    nameKo: "산업생산 (전년비)",
    series: "indpro_yoy",
    source: "FRED", seriesId: "INDPRO",
    freq: "m",
    portalTransform: "yoy",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 440,
    enabled: true,
  },
  {
    code: "unrate",
    nameKo: "실업률",
    series: "unrate",
    source: "FRED", seriesId: "UNRATE",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 439,
    enabled: true,
  },
  {
    code: "sahm",
    nameKo: "SAHM 침체 규칙",
    series: "sahm",
    source: "FRED", seriesId: "SAHMREALTIME",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 439,
    enabled: true,
  },
  {
    code: "nfp_mom",
    nameKo: "비농업 고용 (월간 증감)",
    series: "nfp_mom",
    source: "FRED", seriesId: "PAYEMS",
    freq: "m",
    portalTransform: "momdiff",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-01",
    points: 440,
    enabled: true,
  },
  {
    code: "claims",
    nameKo: "신규 실업수당 청구",
    series: "claims",
    source: "FRED", seriesId: "ICSA",
    freq: "w",
    portalTransform: "levelK",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "1990-01-06",
    points: 1915,
    enabled: true,
  },
  {
    code: "jolts",
    nameKo: "JOLTS 구인건수",
    series: "jolts",
    source: "FRED", seriesId: "JTSJOL",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    historyStart: "2000-12-01",
    points: 308,
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────────
  // 정의는 남기고 끈 것들 (단계 2 지시 · 명세 §C-2).
  // ⚠ 커버리지 **분모에는 남는다.** 못 채우는 자리를 0점으로 메우지 않되,
  //    「안 본 것」이 「괜찮은 것」이 되지도 않게 한다.
  // ────────────────────────────────────────────────────────────────────────
  {
    code: "nfci_credit",
    nameKo: "시카고 연준 금융여건 — 신용 하위지수",
    series: "nfci_credit",
    source: "FRED",
    seriesId: "NFCICREDIT",
    freq: "w",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 156,
    maxWindow: WINDOW_OBS.w,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1971-01-08",
    points: 0,
    enabled: false,
    disabledReason:
      "아직 수집하지 않는다. CREDIT 채널의 장기 골격으로 쓸 계열 — 1971년부터 2,906점(2026-09-19 FRED 확인). P1에서 붙인다.",
  },
  {
    code: "delinquency_ci",
    nameKo: "은행 기업대출 연체율",
    series: "delinquency_ci",
    source: "FRED",
    seriesId: "DRBLACBS",
    freq: "q",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: ["CREDIT"],
    evidence: "official",
    historyStart: "1987-01-01",
    points: 0,
    enabled: false,
    disabledReason:
      "아직 수집하지 않는다. 명세 §C-2의 default rate 대안이자 §2-11 조류 승격의 「구조·실물 확인」 지표. 1987년부터 158점. P1에서 붙인다.",
  },
  {
    code: "tsy_bill_share",
    nameKo: "시장성 국채 중 단기물 비중",
    series: "tsy_bill_share",
    source: "TREASURY",
    seriesId: "mspd:bill_share",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "official",
    historyStart: "2013-01-31",
    points: 152,
    enabled: false,
    disabledReason:
      "⚠ 부호가 정해지지 않았다. 단기물 비중이 커지는 것은 듀레이션 부담을 덜어 유동성에 우호이면서 동시에 차환 위험이다. v1 엔진도 같은 이유로 「표시만 하고 점수에 넣지 않는다」(운영자 결정 2026-09-14). 방향을 정하기 전에는 켜지 않는다.",
  },
  {
    code: "prys",
    nameKo: "생산성 − 실질금리 (PRYS)",
    series: "prys",
    source: "DERIVED",
    freq: "q",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "official",
    // 운영 D1 실측(2026-09-25): 실질 10년(DFII10)이 2003-01-02부터라, 첫 분기(2003-01-01)는 그날 이전 값이 없어 빠진다.
    historyStart: "2003-04-01",
    points: 92,
    historyNote:
      "파생 계열 — `MacroPoint`에 저장하지 않고 읽을 때 합성한다(prod_yoy − real10). 점 수는 prod_yoy 분기 중 real10이 있는 것(93 − 첫 분기 1).",
    // ⭐ 2026-09-25 켰다 — `sectors/supply.ts`의 파생 계열 `prys`(OPHNFB 전년비 − DFII10). 2003년부터.
    enabled: true,
  },
  {
    code: "sector_breadth",
    nameKo: "섹터 폭 (200일선 위 비율)",
    series: "sector_breadth",
    source: "DERIVED",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["PRICE"],
    evidence: "market",
    historyStart: null,
    points: 0,
    enabled: false,
    disabledReason: "섹터 ETF 13개는 받고 있으나 폭 파생을 아직 만들지 않았다(v1 `inputs.ts`도 같은 상태).",
  },
  {
    code: "gpr",
    nameKo: "지정학 위험 지수 (GPR)",
    series: "gpr",
    source: "MANUAL",
    freq: "m",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 60,
    maxWindow: WINDOW_OBS.m,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "judgment",
    historyStart: null,
    points: 0,
    enabled: false,
    disabledReason:
      "Caldara–Iacoviello GPR(무료 · 인용 의무). 어댑터가 없다 — v1 `inputs.ts`에도 「planned」로 남아 있다.",
  },
  {
    code: "cofer",
    nameKo: "세계 외환보유액 중 달러 비중 (COFER)",
    series: "cofer",
    source: "MANUAL",
    freq: "q",
    portalTransform: "level",
    transform: "level",
    polarity: 1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 20,
    maxWindow: WINDOW_OBS.q,
    winsor: [0.01, 0.99],
    channels: [],
    evidence: "manual",
    historyStart: null,
    points: 0,
    enabled: false,
    disabledReason:
      "IMF 분기 · 발표 지연. ⚠ 지연 폭은 구현 시점에 IMF 일정으로 재확인한다 — 명세 부록도 확정하지 않았다. 조류에만 참여할 지표다.",
  },
  {
    code: "move",
    nameKo: "MOVE 지수",
    series: "move",
    source: "MANUAL",
    freq: "d",
    portalTransform: "level",
    transform: "level",
    polarity: -1,
    scaler: "pct_rank",
    window: "expanding",
    minObs: 750,
    maxWindow: WINDOW_OBS.d,
    winsor: [0.01, 0.99],
    channels: ["RATES"],
    evidence: "market",
    historyStart: null,
    points: 0,
    enabled: false,
    disabledReason:
      "⚠ 쓰지 않는다. ICE 라이선스라 무료 시계열이 없고, 대안이 이미 있다 — `ust10y_rvol`(10년물 20일 실현변동성)이 같은 것을 잰다. 자리만 남긴다.",
  },
];

/** 코드 → 정의. ⚠ 같은 코드가 두 번 나오면 검증기가 잡는다. */
export const GCRM_INDICATOR_BY_CODE = new Map(GCRM_INDICATORS.map((i) => [i.code, i]));

/** 실제로 계산에 들어가는 지표. */
export function enabledIndicators(): GcrmIndicator[] {
  return GCRM_INDICATORS.filter((i) => i.enabled);
}

/**
 * 이 지표가 참여하는 축 (§2-4).
 * - 분기·월간 지표는 **조류에만** — 억지로 주간화하지 않는다
 * - 주간 지표는 조류·바람에만
 * ⚠ 나머지 축에서는 0점이 아니라 `MISSING`이다(분모에서 빠진다).
 */
export function axesFor(freq: Freq): ("tide" | "wind" | "wave")[] {
  if (freq === "q" || freq === "m") return ["tide"];
  if (freq === "w") return ["tide", "wind"];
  return ["tide", "wind", "wave"];
}
